apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: '1'
  name: authentication-service
  namespace: shared-services
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  selector:
    matchLabels:
      app: authentication-service
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 20%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        armsPilotAutoEnable: 'on'
        armsPilotCreateAppName: authentication-provider
        k8s.aliyun.com/eci-ram-role-name: varton-test
      labels:
        app: authentication-service
    spec:
      containers:
        - image: >-
            registry-vpc.cn-hangzhou.aliyuncs.com/sfdc_china_dev/authentication-provider:0.0.26
          imagePullPolicy: Always
          env:
            - name: NacosServerAddr
              value: 'mse-18cc11a0-p.nacos-ans.mse.aliyuncs.com:8848'
            - name: mainServiceRamRoleName
              value: varton-test
          name: authentication-service
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 6061

            initialDelaySeconds: 30
            timeoutSeconds: 30
            periodSeconds: 30
          livenessProbe:
            httpGet:
              # scheme: HTTPS
              path: /actuator/health
              port: 6061
            initialDelaySeconds: 30
            timeoutSeconds: 30
            periodSeconds: 30
            successThreshold: 1
            failureThreshold: 3
          resources:
            requests:
              memory: 4Gi
              cpu: "2"
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: authentication-service-hpa
  namespace: shared-services
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: authentication-service
  minReplicas: 1
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 70
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70