{{ $canaryTag := default "" (trimPrefix "-" .Values.versionTag) }}
{{ $suffix := ternary (printf "-%s" $canaryTag) $canaryTag (ne "" $canaryTag) }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: varton-test-gateway
  namespace: varton{{ $suffix }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: varton-test-gateway
  template:
    metadata:
      {{ if .Values.canary }}annotations:
        alicloud.service.tag: "{{ $canaryTag }}"
        msePilotAutoEnable: "on"
        msePilotCreateAppName: varton-test-gateway{{ end }}
      labels:
        app: varton-test-gateway
    spec:
      containers:
        - env:
            {{ if .Values.canary }}- name: SERVICE_TAG
              value: {{ $canaryTag }}
            - name: profiler.micro.service.tag.trace.enable
              value: "true"{{ end }}
            - name: spring.cloud.nacos.config.group
              value: DEFAULT_GROUP{{ $suffix }}
            - name: NACOS_SERVER
              value: 127.0.0.1:8848
          image: registry.cn-hangzhou.aliyuncs.com/local_dev_env/varton-test-gateway:{{ .Values.gatewayTag }}
          imagePullPolicy: Always
          name: varton-test-gateway
---
apiVersion: v1
kind: Service
metadata:
  name: varton-test-gateway
  namespace: varton{{ $suffix }}
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
      name: http
  selector:
    app: varton-test-gateway
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: varton-test-gateway-ingress
  namespace: varton{{ $suffix }}
  labels:
    app.kubernetes.io/name: ack-ingress-nginx
    app.kubernetes.io/instance: api-ingress
    app.kubernetes.io/component: controller
    {{ if .Values.canary }}custom-canary-release-name: varton{{ end }}
  annotations:
    #注意这里要设置为您前面配置的INGRESS_CLASS。
    kubernetes.io/ingress.class: "api-backend"
    nginx.ingress.kubernetes.io/cors-allow-headers: 'content-type, x-org-id'
    nginx.ingress.kubernetes.io/cors-allow-origin: 'https://app{{ .Values.envTag }}.{{ .Values.domainName }}'
    nginx.ingress.kubernetes.io/enable-cors: 'true'
    {{ if .Values.canary }}
    nginx.ingress.kubernetes.io/canary: "true"
    nginx.ingress.kubernetes.io/canary-by-header: "X-ORG-ID"
    nginx.ingress.kubernetes.io/canary-by-header-pattern: ""
    nginx.ingress.kubernetes.io/canary-weight: "0"
    custom-canary-status: "ready"
    custom-canary-tag: "{{ $canaryTag }}"{{ end }}
spec:
  rules:
    - host: internal-api.dev.tableau-shanghai-test.com
      http:
        paths:
          - path: /storefront
            backend:
              serviceName: varton-test-gateway
              servicePort: 80