{{ $canaryTag := default "" (trimPrefix "-" .Values.versionTag) }}
{{ $suffix := ternary (printf "-%s" $canaryTag) $canaryTag (ne "" $canaryTag) }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: varton-test-storefront
  namespace: varton{{ $suffix }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: varton-test-storefront
  template:
    metadata:
      {{ if .Values.canary }}annotations:
        alicloud.service.tag: "{{ $canaryTag }}"
        msePilotAutoEnable: "on"
        msePilotCreateAppName: varton-test-storefront{{ end }}
      labels:
        app: varton-test-storefront
    spec:
      containers:
        - env:
            {{ if .Values.canary }}- name: SERVICE_TAG
              value: {{ $canaryTag }}
            - name: profiler.micro.service.tag.trace.enable
              value: "true"{{ end }}
            - name: spring.cloud.nacos.config.group
              value: DEFAULT_GROUP{{ $suffix }}
            - name: NACOS_SERVER
              value: 127.0.0.1:8848
          image: registry.cn-hangzhou.aliyuncs.com/local_dev_env/varton-test-storefront:{{ .Values.storefrontTag }}
          imagePullPolicy: Always
          name: varton-test-storefront
---
apiVersion: v1
kind: Service
metadata:
  name: varton-test-storefront
  namespace: varton{{ $suffix }}
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
      name: http
  selector:
    app: varton-test-storefront
  type: NodePort